### ISSUE TITLE
`axios 1.1.3` 在APP真机运行报错：Cannot read property 'FormData' of undefined

### ISSUE THREAD

**Issue by aboutZZ** [zxfd/uniapp-axios-adapter#2]
```
E/weex: reportJSException >>>> instanceId:1, exception function:createInstanceContext, exception:Uncaught TypeError: Cannot read property 'FormData' of undefined
        at  (app-service.js:2:62613)
        at  (app-service.js:8:820162)
E/weex: onJSException -9700,Uncaught TypeError: Cannot read property 'FormData' of undefined
        at  (app-service.js:2:62613)
        at  (app-service.js:8:820162)
E/weex: commitCriticalExceptionRT :WX_RENDER_ERR_JS_CREATE_INSTANCE_CONTEXTexceptionwhite screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot read property 'FormData' of undefined
        at  (app-service.js:2:62613)
        at  (app-service.js:8:820162)
```

暂时滚回到 `0.27.2`版本了，等待大神修复

**Comment by zxfd** [comment]
0.27.2不报这个错吗

**Comment by aboutZZ** [comment]
> 0.27.2不报这个错吗

`0.27.2` 没有报错。
这个问题感觉咱们是无能为力了。
应该是 `Hbuilder` 或者 `rollup.js` 编译的问题。稍后我提交个 issue 看看他们怎么回复

**Comment by zxfd** [comment]
> 
跟Hb应该没关系，我用vite+vue3那个模板，高版本的axios也会报错。
我感觉应该是axios的问题，回退axios版本就可以运行，说明问题在axios这里呀。

**Comment by aboutZZ** [comment]
**UPDATE**
最近升级了`axios 1.4.0`, 问题已解决，不再报错
